### ISSUE TITLE
Setup globally

### ISSUE THREAD

**Issue by epodivilov** [igor-dv/jest-specific-snapshot#14]
I tried to install this extension globally in the jest configuration file but got the following error:
`
    ReferenceError: afterAll is not defined
`

Can you explain, how I can add "toMatchSpecificSnapshot" globally?

[Update] It seems that I managed to do what I need using the "setupTestFrameworkScriptFile" parameter in the configuration file. It work for Jest v.22

**Comment by igor-dv** [comment]
Mind share how it works for you?

**Comment by epodivilov** [comment]
I just add this code into jest configuration
`
setupTestFrameworkScriptFile: 'jest-specific-snapshot'
`

After that I can use _toMatchSpecificSnapshot_ everywhere.

At the beginning I tried to import your library in section _setupFiles_ in jest configuration, bu got the above error.

**Comment by igor-dv** [comment]
Thanks
