### ISSUE TITLE
stop hiding documentation behind medium.com paywall

### ISSUE THREAD

**Issue by milahu** [igor-dv/jest-specific-snapshot#26]
> You can read about the implementation [here](https://medium.com/@davydkin.igor/adding-multi-snapshot-testing-to-jest-b61f23cf17ca)

medium.com has the bad habit of hiding content behind paywalls
please copy documentation to github repo / wiki / pages

**Comment by igor-dv** [comment]
The documentation is in github. what is missing for you ? the only thing in medium is just a blog post about the implementation.

**Comment by milahu** [comment]
> a blog post about the implementation.

this is missing

**Comment by igor-dv** [comment]
what is missing ? a blog post ? have you seen blog posts in github ? I would like to see how to do this.

**Comment by milahu** [comment]
> what is missing ?

details on the implementation .. why, how, where, etc
useful info for anyone who wants to hack on this code

```
#!/bin/bash

cd jest-specific-snapshot

# create empty branch gh-pages
# https://gist.github.com/ramnathv/2227408#gistcomment-2915143
git checkout --orphan gh-pages
# preview files to be deleted
git rm -rf --dry-run .
# actually delete the files
git rm -rf .

# add text + images
echo '# Adding multi-snapshot testing to Jest' >index.md
# ....

git commit -a -m init
```

**Comment by shilman** [comment]
It's not behind a paywall -- that medium post is public

**Comment by igor-dv** [comment]
I guess I am closing this.
