### ISSUE TITLE
jest-specific-snapshot@npm:4.0.0: The remote archive doesn't match the expected checksum

### ISSUE THREAD

**Issue by buggedcom** [igor-dv/jest-specific-snapshot#29]
There seems to be something wrong here installing via yarn berry.

```
➤ YN0018: │ jest-specific-snapshot@npm:4.0.0: The remote archive doesn't match the expected checksum
```

```
// package.json
"jest-specific-snapshot": "^4.0.0",
```

**Comment by buggedcom** [comment]
Not sure if it is an issue or not. Looks like it might have been my cache.
https://yarnpkg.com/advanced/error-codes#yn0018---cache_checksum_mismatch

as running `YARN_CHECKSUM_BEHAVIOR=update yarn install` fixed it

**Comment by igor-dv** [comment]
🤔  thanks, lmk if something is still wrong
