### ISSUE TITLE
    TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by bannier** [igor-dv/jest-specific-snapshot#8]
running storybook/addon-storyshots@3.3.15 that depends on jest-specific-snapshot I get this weird behavior : 

```
    TypeError: Cannot read property 'close' of undefined

    > 3 | import initStoryshots from '@storybook/addon-storyshots';
      
      at Object.<anonymous> (node_modules/chalk/index.js:72:74)
      at Object.<anonymous> (node_modules/jest-specific-snapshot/dist/index.js:12:21)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:29:1)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:18:19)
```

looks like at line 12 jest-specific-snapshot/dist/index.js is only importing jest-snapshot
```
var _jestSnapshot = require('jest-snapshot');
```

Any idea why I get this error ?

I'm using `jest-snapshot@22.4.0`

**Comment by igor-dv** [comment]
Do you have a repo where I can reproduce the problem?

**Comment by bannier** [comment]
Sorry no : this is on a private repo. But I can try to reproduce this in another repo if you think it'll help.

**Comment by igor-dv** [comment]
Yeah, it will help. I didn't manage to reproduce this with the examples here

**Comment by igor-dv** [comment]
@bannier, did you manage to reproduce it in a separate repo?

**Comment by igor-dv** [comment]
Please reopen, when you have a reproduction. Thanks.
